plugins {
	id 'java'
	id 'org.springframework.boot' version '3.3.6'
	id 'io.spring.dependency-management' version '1.1.7'
	id "org.openapi.generator" version "7.6.0"

}

group = 'com.example'
version = '0.0.1-SNAPSHOT'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(21)
	}
}

repositories {
	mavenCentral()
}

dependencies {

	// Web
	implementation 'org.springframework.boot:spring-boot-starter-web'

	// JPA
	implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
	implementation 'io.swagger.core.v3:swagger-annotations:2.2.22'
	implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:2.5.0'
	implementation 'org.openapitools:jackson-databind-nullable:0.2.6'


	// PostgreSQL Driver
	runtimeOnly 'org.postgresql:postgresql'

	// Lombok
	compileOnly 'org.projectlombok:lombok'
	annotationProcessor 'org.projectlombok:lombok'

	// Optional: Testing
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'

//	testImplementation 'org.springframework.boot:spring-boot-starter-test'
}

openApiGenerate {
	generatorName = "spring"
	inputSpec = "$rootDir/src/main/resources/openapi.yaml"
	outputDir = "$buildDir/generated"
	apiPackage = "com.example.api"
	modelPackage = "com.example.model"
	invokerPackage = "com.example.invoker"
	configOptions = [
			interfaceOnly: "true",
			useSpringBoot3: "true",
			dateLibrary: "java8"
	]
}

sourceSets {
	main {
		java {
			srcDir "$buildDir/generated/src/main/java"
		}
	}
}

//tasks.named('test') {
////	useJUnitPlatform()
//}
tasks.named("compileJava") {
	dependsOn(tasks.openApiGenerate)
}
test {
	failOnNoDiscoveredTests = false
}




